### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GorIvanov** [ManuelLerchner/neural-network-rs#1]
I have tried to update XOR to use for array with N input and 2 output, but got an error. 
Code:

```
pub static XOR: Dataset = Dataset {
    name: "XOR",
    dataset_type: DatasetType::Static(|| {
        let x = array![
            [0.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 1.0],
            [1.0, 0.0, 1.0, 0.0],
            [1.0, 1.0, 1.0, 1.0]
        ];
        let y = array![[0.0,0.0], [1.0,1.0], [1.0,1.0], [0.0,0.0]];
        (x, y)
    }),
};
```

I have got error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `2`: Input shape does not match data', src\neural_network.rs:130:9
```

How to fix this in my case?

**Comment by ManuelLerchner** [comment]
It seems like you have figured it out yourself. :)

If I had to guess, your problem was that you forgot to change the dimensions of the neural-network so that the input layer can actually accept vectors of size 4. (Maybe the error message should be clearer...)
